server:
  shutdown: graceful

application:
  title: main-server

spring:
  application:
    name: ${application.title}
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${datasource.url}/spring_module_x_${spring.config.activate.on-profile}?serverTimezone=UTC&characterEncoding=UTF-8
    username: spring_module_x_${spring.config.activate.on-profile}
    password: spring_module_x_${spring.config.activate.on-profile}!@34
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        highlight_sql: true
        default_batch_fetch_size: 100

file-path:
  root: ${file-path.application-root}/${spring.application.name}
  upload:
    root: ${file-path.application-root}/uploads
    file: ${file-path.upload.root}/file

logging:
  file:
    path: ${file-path.root}/logs
    name: ${spring.config.activate.on-profile}
  config: classpath:logback-${spring.config.activate.on-profile}.xml

---
# LOCAL
server:
  port: 10001
datasource:
  url: localhost:13306

spring:
  config:
    activate:
      on-profile: local

file-path:
  application-root: /Users/ds/Downloads/springboot/${application.title}

---
# TEST
server:
  port: 10001
datasource:
  url: localhost:13306

spring:
  config:
    activate:
      on-profile: test

file-path:
  application-root: /Users/ds/Downloads/springboot/${application.title}

---
# STAGING
server:
  port: 10002
datasource:
  url: localhost:13306

spring:
  config:
    activate:
      on-profile: staging

file-path:
  application-root: /Users/ds/Downloads/springboot/${application.title}

---
# PROD
server:
  port: 10003
datasource:
  url: localhost:13306

spring:
  config:
    activate:
      on-profile: prod

file-path:
  application-root: /Users/ds/Downloads/springboot/${application.title}