server:
  shutdown: graceful

application:
  title: spring-module-x

spring:
  application:
    name: main-server
  datasource:
    #    driver-class-name: org.mariadb.jdbc.Driver
    #    url: jdbc:mariadb://${datasource.url}/spring_module_x_${spring.config.activate.on-profile}?serverTimezone=UTC&characterEncoding=UTF-8
    #    username: spring_module_x_${spring.config.activate.on-profile}
    #    password: spring_module_x_${spring.config.activate.on-profile}!@34
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${datasource.url}/spring_module_x_${spring.config.activate.on-profile}
    username: spring_module_x_${spring.config.activate.on-profile}
    password: spring_module_x_${spring.config.activate.on-profile}!@34
  data:
    web:
      pageable:
        default-page-size: 20
        one-indexed-parameters: true
  jpa:
    open-in-view: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public
        show_sql: false
        format_sql: false
        highlight_sql: true
        default_batch_fetch_size: 100

file-path:
  root: ${file-path.application-root}/${spring.application.name}
  upload:
    root: ${file-path.application-root}/uploads
    file: ${file-path.upload.root}/file

logging:
  file:
    path: ${file-path.root}/logs
    name: ${spring.config.activate.on-profile}
  config: classpath:logback-spring.xml

---
# LOCAL
server:
  port: 12001
datasource:
  url: localhost

spring:
  config:
    activate:
      on-profile: local

file-path:
  application-root: /Users/ds/Downloads/springboot/${application.title}

---
# TEST
server:
  port: 12001
datasource:
  url: localhost

spring:
  config:
    activate:
      on-profile: test

file-path:
  application-root: /Users/ds/Downloads/springboot/${application.title}

---
# STAGING
server:
  port: 22001
datasource:
  url: localhost

spring:
  config:
    activate:
      on-profile: staging

file-path:
  application-root: /Users/ds/Downloads/springboot/${application.title}

---
# PROD
server:
  port: 32001
datasource:
  url: localhost

spring:
  config:
    activate:
      on-profile: prod

file-path:
  application-root: /Users/ds/Downloads/springboot/${application.title}