# JOOQ
server:
  port: 0
  shutdown: graceful

spring:
  profiles:
    active: generate
  main:
    web-application-type: none
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/spring_module_x_${spring.profiles.active}?serverTimezone=UTC&characterEncoding=UTF-8
    username: spring_module_x_${spring.profiles.active}
    password: spring_module_x_${spring.profiles.active}!@34
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        highlight_sql: true