# JOOQ
server:
  port: 0
  shutdown: graceful

spring:
  profiles:
    active: generate
  main:
    web-application-type: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/spring_module_x_${spring.profiles.active}
    username: spring_module_x_${spring.profiles.active}
    password: spring_module_x_${spring.profiles.active}!@34
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: public
        highlight_sql: true

logging:
  level:
    org.hibernate.SQL: debug